FROM ${BASE_IMAGE}
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get -q update && apt-get -y upgrade 
RUN apt-get install -y wget openjdk-${JRE}-jre
COPY luna-client-${LUNA} /usr/src/luna-client
WORKDIR /usr/src/luna-client
RUN apt-get install -y procps softhsm2 opensc libengine-pkcs11-openssl build-essential vim libssl-dev
RUN ./deb.sh
RUN test -f /usr/lib/libcklog2.so || ln -s /usr/safenet/lunaclient/lib/libcklog2.so /usr/lib/libcklog2.so
RUN rm -rf /usr/src/luna-client
COPY luna-init.sh /
RUN chmod a+rx /luna-init.sh
